exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
name: "Andy Vs Dano : Rematch"
markdown: redcarpet
pygments: true
baseurl: /andyvsdano
shortname url: http://andyvsdano.com